name: DeltaSkins
main: com.gmail.tracebachi.DeltaSkins.Spigot.DeltaSkins
author: GeeItsZee (tracebachi@gmail.com)
version: ${project.version}
commands:
  deltaskins:
    aliases: [ds]
    description: 'Administrative command for DeltaSkins.'
permissions:
  DeltaSkins.check:
    description: 'Check if skin data exists in cache.'
  DeltaSkins.drop:
    description: 'Remove skin data from cache.'
  DeltaSkins.set:
    description: 'Set skin data for someone using skin data in cache.'
  DeltaSkins.update:
    description: 'Force an update of skin data in cache.'
